//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageBox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageBox.Resources.Entities", typeof(Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ACCOUNT_ACTIVE_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_ACTIVE_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ACCOUNT_APPLICATION_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_APPLICATION_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication retries.
        /// </summary>
        internal static string ACCOUNT_AUTHENTICATIONRETRIES_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_AUTHENTICATIONRETRIES_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string ACCOUNT_BLOCKED_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_BLOCKED_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked on.
        /// </summary>
        internal static string ACCOUNT_BLOCKEDON_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_BLOCKEDON_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string ACCOUNT_CREATEDBY_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_CREATEDBY_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string ACCOUNT_CREATEDON_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_CREATEDON_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated by.
        /// </summary>
        internal static string ACCOUNT_DEACTIVATEDBY_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_DEACTIVATEDBY_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated on.
        /// </summary>
        internal static string ACCOUNT_DEACTIVATEDON_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_DEACTIVATEDON_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ACCOUNT_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last authentication on.
        /// </summary>
        internal static string ACCOUNT_LASTAUTHENTICATIONON_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_LASTAUTHENTICATIONON_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        internal static string ACCOUNT_MODIFIEDBY_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_MODIFIEDBY_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified on.
        /// </summary>
        internal static string ACCOUNT_MODIFIEDON_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_MODIFIEDON_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ACCOUNT_NAME_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ACCOUNT_PASSWORD_DISPLAYNAME {
            get {
                return ResourceManager.GetString("ACCOUNT_PASSWORD_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application key.
        /// </summary>
        internal static string APPLICATION_APPLICATIONKEY_DISPLAYNAME {
            get {
                return ResourceManager.GetString("APPLICATION_APPLICATIONKEY_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string APPLICATION_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("APPLICATION_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string APPLICATION_NAME_DISPLAYNAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string MIMETYPE_EXTENSION_DISPLAYNAME {
            get {
                return ResourceManager.GetString("MIMETYPE_EXTENSION_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string MIMETYPE_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("MIMETYPE_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media type.
        /// </summary>
        internal static string MIMETYPE_MEDIATYPE_DISPLAYNAME {
            get {
                return ResourceManager.GetString("MIMETYPE_MEDIATYPE_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string SESSION_ACCOUNT_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SESSION_ACCOUNT_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string SESSION_DEVICE_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SESSION_DEVICE_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string SESSION_ENABLED_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SESSION_ENABLED_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string SESSION_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SESSION_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session uuid.
        /// </summary>
        internal static string SESSION_SESSIONUUID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SESSION_SESSIONUUID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started on.
        /// </summary>
        internal static string SESSION_STARTEDON_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SESSION_STARTEDON_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string STORAGEFILE_EXTENSION_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_EXTENSION_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string STORAGEFILE_FILENAME_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_FILENAME_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        internal static string STORAGEFILE_FILESIZE_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_FILESIZE_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uuid.
        /// </summary>
        internal static string STORAGEFILE_FILEUUID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_FILEUUID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string STORAGEFILE_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string STORAGEFILE_SESSION_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_SESSION_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage path.
        /// </summary>
        internal static string STORAGEFILE_STORAGEPATH_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_STORAGEPATH_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded on.
        /// </summary>
        internal static string STORAGEFILE_UPLOADEDON_DISPLAYNAME {
            get {
                return ResourceManager.GetString("STORAGEFILE_UPLOADEDON_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string SYSTEMCONFIGURATION_ID_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SYSTEMCONFIGURATION_ID_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        internal static string SYSTEMCONFIGURATION_PARAMETERNAME_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SYSTEMCONFIGURATION_PARAMETERNAME_DISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value.
        /// </summary>
        internal static string SYSTEMCONFIGURATION_PARAMETERVALUE_DISPLAYNAME {
            get {
                return ResourceManager.GetString("SYSTEMCONFIGURATION_PARAMETERVALUE_DISPLAYNAME", resourceCulture);
            }
        }
    }
}
